Logging:
  LogLevel:
    Default: Trace
Lifecycle:
  ResetOnAppFailure: false
Update:
  UpdateServer: mqtt.meadowcloud.co
  UpdatePort: 8883
  AuthServer: https://staging.meadowcloud.dev
  AuthPort: 443
  Enabled: true
  UseAuthentication: true