Settings:
    APN: YOUR-APN         # (required) Access Point Name
    Module: BG95M3        # (required) Module model (BG770A, BG95M3 or M95)
    User: USER            # (optional) APN user 
    Password: PASSWORD    # (optional) APN password
    Operator: 00000       # (optional) Carrier numeric operator code
    Mode: CATM1           # (optional) Network mode (CATM1, NBIOT or GSM)
    Interface: /dev/ttyS0 # (required) Serial interface 
                          # UART1 (COM1) = /dev/ttyS0 (default)
                          # UART4 (COM4) = /dev/ttyS1, 
                          # UART6 = /dev/ttyS3 
    TurnOnPin: A3         # (required) Turn-on MCU pin to power the module on/off.
                          # Default value is MCU Pin A3

                          # IMPORTANT: 
                          # Ensure to use the MCU pin names, not the Meadow pin names (seen on the board)
                          #
                          #  Examples:
                          #  Using mikroBUS 1 on Project Lab v3 with Quectel BG95-M3 (Meadow AN pin as Turn-on pin):
                          #   TurnOnPin: A3
                          #
                          #  Using mikroBUS 1 on Project Lab v3 with Quectel M95 (Meadow RST pin as Turn-on pin):
                          #   TurnOnPin: H10
                          #
                          #  Using Meadow D10 pin as Turn-on pin on F7FeatherV2 with BG95-M3 or M95: 
                          #   TurnOnPin: C7
                          #
                          # For a custom setup, consult the pinout definition on your 
                          #  Meadow device datasheet for the correct MCU pin names


