#
#   Device specific config.
#
Device:
    #
    #   Name of the device on the network.
    #
    Name: TLSClientAuthentication

Coprocessor:

    # Should the ESP32 automatically attempt to connect to an access point at startup?
    # If set to true, wifi.config.yaml credentials must be stored in the device.

    AutomaticallyStartNetwork: true
#
#   Network configuration.
#
Network:
    Interfaces:
        - Name: WiFi
          UseDHCP: true
    #
    #   Which interface should be used?
    #
    DefaultInterface: WiFi